image_path: directiory folder to the images
classication_labels_path: path to Data_Entry_2017.csv
localization_labels_path: path to Bbox_List_2017.csv
results_path: folder where results are stored
processed_labels_path: path to preprocessed csv processed_Y.csv
skip_processing_labels: false/true